# Generated by Django 6.1.1 on 2026-10-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_school_education_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.schooltype'),
        ),
    ]
