# Generated by Django 6.1.1 on 2026-10-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_school_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.country'),
        ),
    ]
