# Generated by Django 6.1.1 on 2026-10-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_school_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
