# Generated by Django 6.1.1 on 2026-10-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_school_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(),
        ),
    ]
