# Generated by Django 6.1.1 on 2026-10-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_school_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
