# Generated by Django 6.1.1 on 2026-10-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_alter_school_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
