# Generated by Django 6.1.1 on 2026-10-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_school_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='hotline',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
