# Generated by Django 6.1.1 on 2026-10-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_school_hotline'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
