# Generated by Django 6.1.1 on 2026-10-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_school_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
    ]
