# Generated by Django 6.1.1 on 2026-10-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_school_created_at_school_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
