# Generated by Django 6.1.1 on 2026-10-01 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0026_staffrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='job_title',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schools.staffrole'),
        ),
    ]
