# Generated by Django 6.1.1 on 2026-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0032_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
