# Generated by Django 6.1.1 on 2026-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0033_school_school_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
