# Generated by Django 6.1.1 on 2026-10-02 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0035_studentnumbersequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_or_passport', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('TRANSFERRED', 'Transferred'), ('EXPELLED', 'Expelled')], default='ACTIVE', max_length=20)),
                ('student_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('academic_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.schoolacademiclevel')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.classroom')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.country')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
